kind: pipeline
type: kubernetes
name: default
steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      repo:
        from_secret: DOCKER_REPO
      registry:
        from_secret: DOCKER_REGISTRY
      auto_tag: true